export const ACT_AUTHEN_LOGIN_REQUEST = "ACT_AUTHEN_LOGIN_REQUEST";
export const ACT_AUTHEN_LOGIN_SUCCESS = "ACT_AUTHEN_LOGIN_SUCCESS";
export const ACT_AUTHEN_LOGIN_FAILURE = "ACT_AUTHEN_LOGIN_FAILURE";
