export const ACT_CREATE_CATEGORY_REQUEST = "ACT_CREATE_CATEGORY_REQUEST";
export const ACT_CREATE_CATEGORY_SUCCESS = "ACT_CREATE_CATEGORY_SUCCESS";
export const ACT_CREATE_CATEGORY_FAILURE = "ACT_CREATE_CATEGORY_FAILURE";

export const ACT_UPDATE_CATEGORY_REQUEST = "ACT_UPDATE_CATEGORY_REQUEST";
export const ACT_UPDATE_CATEGORY_SUCCESS = "ACT_UPDATE_CATEGORY_SUCCESS";
export const ACT_UPDATE_CATEGORY_FAILURE = "ACT_UPDATE_CATEGORY_FAILURE";

export const ACT_GET_CATEGORY_REQUEST = "ACT_GET_CATEGORY_REQUEST";
export const ACT_GET_CATEGORY_SUCCESS = "ACT_GET_CATEGORY_SUCCESS";
export const ACT_GET_CATEGORY_FAILURE = "ACT_GET_CATEGORY_FAILURE";

export const ACT_CHANGE_CREATE_CATE_VISIBLE_STATE =
  "ACT_CHANGE_CREATE_CATE_VISIBLE_STATE";
export const ACT_CHANGE_UPDATE_CATE_VISIBLE_STATE =
  "ACT_CHANGE_UPDATE_CATE_VISIBLE_STATE";
