export const ACT_CREATE_ORDER_REQUEST = "ACT_CREATE_ORDER_REQUEST";
export const ACT_CREATE_ORDER_SUCCESS = "ACT_CREATE_ORDER_SUCCESS";
export const ACT_CREATE_ORDER_FAILURE = "ACT_CREATE_ORDER_FAILURE";

export const ACT_UPDATE_ORDER_REQUEST = "ACT_UPDATE_ORDER_REQUEST";
export const ACT_UPDATE_ORDER_SUCCESS = "ACT_UPDATE_ORDER_SUCCESS";
export const ACT_UPDATE_ORDER_FAILURE = "ACT_UPDATE_ORDER_FAILURE";

export const ACT_GET_ORDER_REQUEST = "ACT_GET_ORDER_REQUEST";
export const ACT_GET_ORDER_SUCCESS = "ACT_GET_ORDER_SUCCESS";
export const ACT_GET_ORDER_FAILURE = "ACT_GET_ORDER_FAILURE";

export const ACT_GET_ORDER_WITHOUT_PAGING_REQUEST =
  "ACT_GET_ORDER_WITHOUT_PAGING_REQUEST";
export const ACT_GET_ORDER_WITHOUT_PAGING_SUCCESS =
  "ACT_GET_ORDER_WITHOUT_PAGING_SUCCESS";
export const ACT_GET_ORDER_WITHOUT_PAGING_FAILURE =
  "ACT_GET_ORDER_WITHOUT_PAGING_FAILURE";

export const ACT_CHANGE_ORDER_NOTI = "ACT_CHANGE_ORDER_NOTI";

export const ACT_CHANGE_UPDATE_ORDER_VISIBLE_STATE =
  "ACT_CHANGE_UPDATE_ORDER_VISIBLE_STATE";
export const ACT_CHANGE_CREATE_ORDER_VISIBLE_STATE =
  "ACT_CHANGE_CREATE_ORDER_VISIBLE_STATE";
