export const ACT_CREATE_PAYMENT_REQUEST = "ACT_CREATE_PAYMENT_REQUEST";
export const ACT_CREATE_PAYMENT_SUCCESS = "ACT_CREATE_PAYMENT_SUCCESS";
export const ACT_CREATE_PAYMENT_FAILURE = "ACT_CREATE_PAYMENT_FAILURE";

export const ACT_UPDATE_PAYMENT_REQUEST = "ACT_UPDATE_PAYMENT_REQUEST";
export const ACT_UPDATE_PAYMENT_SUCCESS = "ACT_UPDATE_PAYMENT_SUCCESS";
export const ACT_UPDATE_PAYMENT_FAILURE = "ACT_UPDATE_PAYMENT_FAILURE";

export const ACT_GET_PAYMENT_REQUEST = "ACT_GET_PAYMENT_REQUEST";
export const ACT_GET_PAYMENT_SUCCESS = "ACT_GET_PAYMENT_SUCCESS";
export const ACT_GET_PAYMENT_FAILURE = "ACT_GET_PAYMENT_FAILURE";

export const ACT_GET_PAYMENT_WITHOUT_PAGING_REQUEST =
  "ACT_GET_PAYMENT_WITHOUT_PAGING_REQUEST";
export const ACT_GET_PAYMENT_WITHOUT_PAGING_SUCCESS =
  "ACT_GET_PAYMENT_WITHOUT_PAGING_SUCCESS";
export const ACT_GET_PAYMENT_WITHOUT_PAGING_FAILURE =
  "ACT_GET_PAYMENT_WITHOUT_PAGING_FAILURE";

export const ACT_SET_RELOAD_PAYMENT = "ACT_SET_RELOAD_PAYMENT";

export const ACT_CHANGE_UPDATE_PAYMENT_VISIBLE_STATE =
  "ACT_CHANGE_UPDATE_PAYMENT_VISIBLE_STATE";
