export const ACT_CREATE_SELLER_REQUEST = "ACT_CREATE_SELLER_REQUEST";
export const ACT_CREATE_SELLER_SUCCESS = "ACT_CREATE_SELLER_SUCCESS";
export const ACT_CREATE_SELLER_FAILURE = "ACT_CREATE_SELLER_FAILURE";

export const ACT_UPDATE_SELLER_REQUEST = "ACT_UPDATE_SELLER_REQUEST";
export const ACT_UPDATE_SELLER_SUCCESS = "ACT_UPDATE_SELLER_SUCCESS";
export const ACT_UPDATE_SELLER_FAILURE = "ACT_UPDATE_SELLER_FAILURE";

export const ACT_GET_SELLER_REQUEST = "ACT_GET_SELLER_REQUEST";
export const ACT_GET_SELLER_SUCCESS = "ACT_GET_SELLER_SUCCESS";
export const ACT_GET_SELLER_FAILURE = "ACT_GET_SELLER_FAILURE";

export const ACT_CHANGE_CREATE_SELLER_VISIBLE_STATE =
  "ACT_CHANGE_CREATE_SELLER_VISIBLE_STATE";
export const ACT_CHANGE_UPDATE_SELLER_VISIBLE_STATE =
  "ACT_CHANGE_UPDATE_SELLER_VISIBLE_STATE";
