export const ACT_GET_STATISTIC_A_USER_SALE_REQUEST =
  "ACT_GET_STATISTIC_A_USER_SALE_REQUEST";
export const ACT_GET_STATISTIC_A_USER_SALE_SUCCESS =
  "ACT_GET_STATISTIC_A_USER_SALE_SUCCESS";
export const ACT_GET_STATISTIC_A_USER_SALE_FAILED =
  "ACT_GET_STATISTIC_A_USER_SALE_FAILED";
